syntax on
filetype plugin indent on

" Tab width = 4
set tabstop=4
" Make < and > indent by 4 columns
set shiftwidth=4
" Replace tabs with spaces
set expandtab
" Line numbers
set number
" Relative line numbers for fast movement and editing
set relativenumber

" XDG compliance
set undodir=~/.cache/vim/undo
set directory=~/.cache/vim/swap
set backupdir=~/.cache/vim/backup
set viminfo+=n~/.cache/vim/viminfo

