" Configure paths
" (XDG compliance)
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set undodir=$XDG_CACHE_HOME/vim/undo
set runtimepath=$XDG_CONFIG_HOME/vim,$VIMRUNTIME,$XDG_CONFIG_HOME/vim/after,$VIM
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

filetype plugin indent on
syntax on

" Tab width = 4
set tabstop=4
" Make < and > indent by 4 columns
set shiftwidth=4
" Replace tabs with spaces
set expandtab
" Line numbers
set number
" yank/delete to system clipboard
set clipboard=unnamedplus
" color columns 80 and 100 to provide a line length marker
" (text on the colored lines is still within bounds)
set colorcolumn=80,100

"""""""""""
" Plugins "
"""""""""""

call plug#begin('~/.local/share/vim/plugged')

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }

Plug 'lervag/vimtex'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

"""""""""""""""
" End Plugins "
"""""""""""""""

" Airline configuration
let g:airline_theme='term'
let g:airline_left_sep=''

" deoplete
let g:deoplete#enable_at_startup = 1

let g:tex_flavor = 'latex'

