" Configure paths
" (XDG compliance)
set directory=$XDG_CACHE_HOME/vim,~/,/tmp
set backupdir=$XDG_CACHE_HOME/vim,~/,/tmp
set viminfo+=n$XDG_CACHE_HOME/vim/viminfo
set undodir=$XDG_CACHE_HOME/vim/undo
set runtimepath=$XDG_CONFIG_HOME/vim,$XDG_CONFIG_HOME/vim/after,$VIM,$VIMRUNTIME
let $MYVIMRC="$XDG_CONFIG_HOME/vim/vimrc"

syntax on
filetype plugin indent on

" Tab width = 4
set tabstop=4
" Make < and > indent by 4 columns
set shiftwidth=4
" Replace tabs with spaces
set expandtab
" Line numbers
set number
" yank/delete to system clipboard
set clipboard=unnamedplus


"""""""""""
" Plugins "
"""""""""""

call plug#begin('~/.local/share/vim/plugged')

Plug 'vim-latex/vim-latex'

" A Vim Plugin for Lively Previewing LaTeX PDF Output
Plug 'xuhdev/vim-latex-live-preview', { 'for': 'tex' }

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

call plug#end()

"""""""""""""""
" End Plugins "
"""""""""""""""

" Airline configuration
let g:airline_theme='term'
let g:airline_left_sep=''

" LaTeX configuration
let g:tex_flavor='latex'

